name: Deploy Hugo a Proxmox
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Configurar Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Compilar sitio (Build)
        run: hugo --minify --baseURL "https://lexvida.com/"
      - name: Enviar archivos al LXC
        uses: easingthemes/ssh-deploy@main
        env: SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/hugo/public/"
          SOURCE: "public/"